import sys

def fail(msg):
    print(msg)
    sys.exit(1)